Inverse mapping mechanism
alekshura/SourceMapper pull request #23
Opened 2021-11-15 08:37 UTC by pszulccompentio

2021-11-30 09:32 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Attributes/InverseAttributeService.cs
> +namespace Compentio.SourceMapper.Attributes
Moved to AttributeMatchers.

2021-11-30 09:32 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Attributes/InverseAttributeService.cs
> +﻿using Compentio.SourceMapper.Diagnostics;
Cleaned.

2021-11-30 09:34 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/InterfaceProcessorStrategy.cs
> +using System;
And the same in ClassProcessorStrategy - cleaned.

2021-11-30 09:34 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/InterfaceProcessorStrategy.cs
> +            if (InverseAttributeService.AnyInverseMethod(mapperMetadata.MethodsMetadata))
Fixed.

2021-11-30 14:22 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Metadata/MethodMetadata.cs
> +                            InverseExpression = inverseExpression.Value as string ?? string.Empty,
I removed those attributes. For more complex mapping, we can override mapping result class as is shown in tests or examples.

2021-11-30 14:23 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/IProcessorStrategy.cs
> +                var inverseMethodName = InverseAttribute.GetInverseMethodName(methodMetadata);
Fixed.

2021-11-30 14:23 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/InterfaceProcessorStrategy.cs
> +        private string GetInverseMethodName(IMethodMetadata methodMetadata)
Moved to MethodMetadata class.

2021-12-01 11:29 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Metadata/MethodMetadata.cs
> +        public virtual IEnumerable<MappingAttribute> MappingAttributes => _methodSymbol.GetAttributes()
Shouldn't be. Fixed.

2021-12-01 11:29 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Attributes/MappingAttribute.cs
> +        public virtual string Target { get; set; } = string.Empty;
I need this for overriting fields in a few unit tests.

2021-12-01 11:30 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Attributes/InverseAttribute.cs
> +    internal static class InverseAttribute
Fixed.

2021-12-01 11:31 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/IProcessorStrategy.cs
> +        protected string GenerateRegularMethod(IMapperMetadata sourceMetadata, IMethodMetadata methodMetadata)
Fixed.

2021-12-01 12:04 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/IProcessorStrategy.cs
> +            if (inverseMapping)
Fixed.

2021-12-01 12:05 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/IProcessorStrategy.cs
Added.

2021-12-01 12:07 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Metadata/PropertyMetadata.cs
> +        public static void Swap(ref IPropertyMetadata sourcePropertyMetadata, ref IPropertyMetadata targetPropertyMetadata)
I moved this method to ObjectHelper class. We need ref because we swaped two reference type objects, not values.

2021-12-01 13:55 UTC, alekshura requested changes

2021-12-01 13:55 UTC, alekshura commented on Compentio.SourceMapper.Generator/Matchers/AttributesMatchers.cs
> +        /// Check that exists any method with the inverse attribute set
```suggestion
        /// Method checks is there any method makked with the <see cref=InverseAttribute/>
```

2021-12-01 13:55 UTC, alekshura commented on Compentio.SourceMapper.Generator/Matchers/AttributesMatchers.cs
> +        /// Check method has inverse method attribute
As earlier: `Metod does smth....`

2021-12-01 13:55 UTC, alekshura commented on Compentio.SourceMapper.Generator/Matchers/AttributesMatchers.cs
> +        /// Get full inverse method name based on original method and inverse method name
Earlier

2021-12-01 13:55 UTC, alekshura commented on Compentio.SourceMapper.Generator/Metadata/MethodMetadata.cs
```suggestion
/// <inheritdoc />
```

2021-12-01 13:55 UTC, alekshura commented on Compentio.SourceMapper.Generator/Processors/IProcessorStrategy.cs
> +        public IResult GenerateCode(IMapperMetadata mapperMetadata)
```suggestion
        /// <inheritdoc />
        public IResult GenerateCode(IMapperMetadata mapperMetadata)
```

2021-12-02 08:12 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Processors/IProcessorStrategy.cs
> +        public IResult GenerateCode(IMapperMetadata mapperMetadata)
Updated.

2021-12-02 08:13 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Metadata/MethodMetadata.cs
Updated.

2021-12-02 08:13 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Matchers/AttributesMatchers.cs
> +        /// Get full inverse method name based on original method and inverse method name
Updated.

2021-12-02 08:13 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Matchers/AttributesMatchers.cs
> +        /// Check method has inverse method attribute
Updated.

2021-12-02 08:13 UTC, pszulccompentio commented on Compentio.SourceMapper.Generator/Matchers/AttributesMatchers.cs
> +        /// Check that exists any method with the inverse attribute set
Updated.

2021-12-02 10:08 UTC, alekshura approved these changes

2021-12-02 10:09 UTC, merged